name: 天翼云盘签到
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '30 5,17 * * *'
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装环境
      run:
        pip install -r requirements.txt
    - name: 签到
      run: |
        python3 ./tyyp.py > output.txt
      env:
        TYYP_USERNAME: ${{ secrets.TYYP_USERNAME }}
        TYYP_PSW: ${{ secrets.TYYP_PSW }}
    - name: 提交更改并推送至 GitHub 页面分支
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add output.txt
        git commit -m "Add output.txt"
        git push
