name: 天翼云盘签到
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 5,17 * * *'
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: 安装环境
      run: |
        pip install datetime

    - name: 签到
      env:
        TYYP_USERNAME: ${{ secrets.TYYP_USERNAME }}  
        TYYP_PSW: ${{ secrets.TYYP_PSW }}
      run: |
        python3 ./tyyp.py

    - name: Remove old markdown
      run: |
        git rm -f 签到结果_*.md

    - name: Upload markdown result  
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update result" -a
        git push
