name: 天翼云盘签到
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 12 6 * * *
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装环境
      run:
        #python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 签到
      run: |
        python3 ./tyyp.py
      env:
        #QYWX_CORPID: ${{ secrets.QYWX_CORPID }}
        #QYWX_CORPSECRET: ${{ secrets.QYWX_CORPSECRET }}
        #QYWX_AGENTID: ${{ secrets.QYWX_AGENTID }}
        TYYP_USERNAME: ${{ secrets.TYYP_USERNAME }}
        TYYP_PSW: ${{ secrets.TYYP_PSW }}
        TZ: Asia/Shanghai
