name: 天翼云盘签到
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '30 5,17 * * *'
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装环境
      run:
        pip install -r requirements.txt
    - name: 签到
      run: |
        python3 ./tyyp.py > output.txt
      env:
        TYYP_USERNAME: ${{ secrets.TYYP_USERNAME }}
        TYYP_PSW: ${{ secrets.TYYP_PSW }}
    - name: 更新 README 
      run: |
        api_url="https://api.github.com/repos/$GITHUB_REPOSITORY/contents/README.md"
        # 构建 README 内容 
        echo "签到结果: $(cat output.txt)" > readme.md
        curl -X PUT -H "Authorization: token $GITHUB_TOKEN" --data-binary @readme.md $api_url
